// Mock property portfolio data.
// Coordinates are real UK locations so the Leaflet map looks plausible.
// Replace with API data when wiring to a real backend.
// Exposed on window so the no-build app.js can read it.

window.SEVERITY_LEVELS = ['Low', 'Medium', 'High', 'Critical'];

window.SIGNAL_TYPES = [
  'Flood risk change',
  'Underinsurance',
  'Valuation drop',
  'EPC downgrade',
  'Listing detected',
  'Subsidence alert',
  'Tenancy change',
  'Insurance gap',
];

window.WORKFLOW_STATUSES = [
  'New',
  'In review',
  'Action required',
  'Awaiting customer',
  'Resolved',
  'Snoozed',
];

window.OWNERS = [
  'Sarah Lee',
  'Tom Harris',
  'Priya Patel',
  'James Whitcombe',
  'Risk Team',
  'Unassigned',
];

window.TENURES = ['Freehold', 'Leasehold', 'Share of Freehold'];
window.EPC_RATINGS = ['A', 'B', 'C', 'D', 'E', 'F', 'G'];

var __today = new Date();
function daysAgo(n) {
  var d = new Date(__today);
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
}

window.PROPERTIES = [
  {
    id: 'p-001',
    address: '12 Downing Street',
    city: 'London',
    postcode: 'SW1A 2AA',
    lat: 51.5034,
    lng: -0.1276,
    severity: 'Critical',
    dateAdded: daysAgo(2),
    signalType: 'Subsidence alert',
    workflowStatus: 'Action required',
    assignedTo: 'Sarah Lee',
    type: 'Townhouse',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2400,
    yearBuilt: 1735,
    estimatedValue: 4250000,
    lastValuation: daysAgo(14),
    tenure: 'Freehold',
    epc: 'D',
    isUnlicensedHmo: false,
    floodRisk: 'Medium',
    notes: 'Listed building. Recent subsidence flagged on neighbouring property.',
  },
  {
    id: 'p-002',
    address: '221B Baker Street',
    city: 'London',
    postcode: 'NW1 6XE',
    lat: 51.5237,
    lng: -0.1585,
    severity: 'High',
    dateAdded: daysAgo(5),
    signalType: 'EPC downgrade',
    workflowStatus: 'In review',
    assignedTo: 'Priya Patel',
    type: 'Flat',
    bedrooms: 2,
    bathrooms: 1,
    sqft: 980,
    yearBuilt: 1815,
    estimatedValue: 1150000,
    lastValuation: daysAgo(30),
    tenure: 'Leasehold',
    epc: 'C',
    isUnlicensedHmo: true,
    floodRisk: 'Low',
    notes: 'Tenant lease expires Q3. EPC upgrade recommended.',
  },
  {
    id: 'p-003',
    address: '4 Privet Drive',
    city: 'Little Whinging, Surrey',
    postcode: 'GU21 5AB',
    lat: 51.3168,
    lng: -0.5601,
    severity: 'Low',
    dateAdded: daysAgo(45),
    signalType: 'Tenancy change',
    workflowStatus: 'Resolved',
    assignedTo: 'Tom Harris',
    type: 'Detached House',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1620,
    yearBuilt: 1985,
    estimatedValue: 685000,
    lastValuation: daysAgo(60),
    tenure: 'Freehold',
    epc: 'B',
    isUnlicensedHmo: false,
    floodRisk: 'Low',
    notes: 'Stable suburban asset. No active alerts.',
  },
  {
    id: 'p-004',
    address: '32 Windsor Gardens',
    city: 'London',
    postcode: 'W9 3RG',
    lat: 51.5226,
    lng: -0.1885,
    severity: 'Medium',
    dateAdded: daysAgo(11),
    signalType: 'Insurance gap',
    workflowStatus: 'New',
    assignedTo: 'Unassigned',
    type: 'Apartment',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 540,
    yearBuilt: 1968,
    estimatedValue: 495000,
    lastValuation: daysAgo(20),
    tenure: 'Leasehold',
    epc: 'D',
    isUnlicensedHmo: false,
    floodRisk: 'Medium',
    notes: 'Cladding remediation pending across the block.',
  },
  {
    id: 'p-005',
    address: '15 Royal Crescent',
    city: 'Bath',
    postcode: 'BA1 2LS',
    lat: 51.3870,
    lng: -2.3674,
    severity: 'Low',
    dateAdded: daysAgo(120),
    signalType: 'Listing detected',
    workflowStatus: 'Snoozed',
    assignedTo: 'James Whitcombe',
    type: 'Georgian Terrace',
    bedrooms: 5,
    bathrooms: 3,
    sqft: 3100,
    yearBuilt: 1774,
    estimatedValue: 2890000,
    lastValuation: daysAgo(75),
    tenure: 'Freehold',
    epc: 'E',
    isUnlicensedHmo: false,
    floodRisk: 'Low',
    notes: 'Grade I listed. Restoration completed 2024.',
  },
  {
    id: 'p-006',
    address: '8 Castle Street',
    city: 'Edinburgh',
    postcode: 'EH2 3AH',
    lat: 55.9521,
    lng: -3.2024,
    severity: 'High',
    dateAdded: daysAgo(7),
    signalType: 'Flood risk change',
    workflowStatus: 'In review',
    assignedTo: 'Risk Team',
    type: 'Mixed Use',
    bedrooms: 0,
    bathrooms: 4,
    sqft: 5200,
    yearBuilt: 1890,
    estimatedValue: 3450000,
    lastValuation: daysAgo(10),
    tenure: 'Freehold',
    epc: 'D',
    isUnlicensedHmo: false,
    floodRisk: 'High',
    notes: 'Commercial tenant default risk. Roof survey overdue.',
  },
  {
    id: 'p-007',
    address: '77 Mosley Street',
    city: 'Manchester',
    postcode: 'M2 3LW',
    lat: 53.4794,
    lng: -2.2410,
    severity: 'High',
    dateAdded: daysAgo(3),
    signalType: 'Valuation drop',
    workflowStatus: 'Action required',
    assignedTo: 'Tom Harris',
    type: 'Office',
    bedrooms: 0,
    bathrooms: 6,
    sqft: 8400,
    yearBuilt: 2008,
    estimatedValue: 5100000,
    lastValuation: daysAgo(8),
    tenure: 'Leasehold',
    epc: 'C',
    isUnlicensedHmo: false,
    floodRisk: 'Medium',
    notes: 'Anchor tenant exit notice received.',
  },
  {
    id: 'p-008',
    address: '3 Albert Dock',
    city: 'Liverpool',
    postcode: 'L3 4AF',
    lat: 53.4002,
    lng: -2.9925,
    severity: 'Medium',
    dateAdded: daysAgo(34),
    signalType: 'Flood risk change',
    workflowStatus: 'Awaiting customer',
    assignedTo: 'Priya Patel',
    type: 'Waterfront Apartment',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    yearBuilt: 2003,
    estimatedValue: 420000,
    lastValuation: daysAgo(40),
    tenure: 'Leasehold',
    epc: 'B',
    isUnlicensedHmo: false,
    floodRisk: 'High',
    notes: 'Annual flood insurance review due.',
  },
  {
    id: 'p-009',
    address: '19 Park Lane',
    city: 'London',
    postcode: 'W1K 1QA',
    lat: 51.5074,
    lng: -0.1530,
    severity: 'Critical',
    dateAdded: daysAgo(1),
    signalType: 'Insurance gap',
    workflowStatus: 'Action required',
    assignedTo: 'Sarah Lee',
    type: 'Penthouse',
    bedrooms: 4,
    bathrooms: 4,
    sqft: 3800,
    yearBuilt: 2015,
    estimatedValue: 12500000,
    lastValuation: daysAgo(5),
    tenure: 'Share of Freehold',
    epc: 'A',
    isUnlicensedHmo: false,
    floodRisk: 'Low',
    notes: 'Insurance premium spike — review immediately.',
  },
  {
    id: 'p-010',
    address: '42 Park Row',
    city: 'Leeds',
    postcode: 'LS1 5JL',
    lat: 53.7997,
    lng: -1.5492,
    severity: 'Medium',
    dateAdded: daysAgo(22),
    signalType: 'Tenancy change',
    workflowStatus: 'In review',
    assignedTo: 'James Whitcombe',
    type: 'Office',
    bedrooms: 0,
    bathrooms: 4,
    sqft: 6800,
    yearBuilt: 1998,
    estimatedValue: 2750000,
    lastValuation: daysAgo(28),
    tenure: 'Leasehold',
    epc: 'C',
    isUnlicensedHmo: false,
    floodRisk: 'Low',
    notes: 'Lease renewal negotiations underway.',
  },
  {
    id: 'p-011',
    address: '5 Park Place',
    city: 'Cardiff',
    postcode: 'CF10 3DP',
    lat: 51.4847,
    lng: -3.1768,
    severity: 'Low',
    dateAdded: daysAgo(88),
    signalType: 'Listing detected',
    workflowStatus: 'Resolved',
    assignedTo: 'Tom Harris',
    type: 'Townhouse',
    bedrooms: 4,
    bathrooms: 2,
    sqft: 2100,
    yearBuilt: 1905,
    estimatedValue: 595000,
    lastValuation: daysAgo(90),
    tenure: 'Freehold',
    epc: 'D',
    isUnlicensedHmo: true,
    floodRisk: 'Low',
    notes: 'Stable. No actions required.',
  },
  {
    id: 'p-012',
    address: '11 Grey Street',
    city: 'Newcastle',
    postcode: 'NE1 6EE',
    lat: 54.9714,
    lng: -1.6131,
    severity: 'Low',
    dateAdded: daysAgo(15),
    signalType: 'EPC downgrade',
    workflowStatus: 'New',
    assignedTo: 'Unassigned',
    type: 'Commercial',
    bedrooms: 0,
    bathrooms: 2,
    sqft: 3200,
    yearBuilt: 1838,
    estimatedValue: 1450000,
    lastValuation: daysAgo(35),
    tenure: 'Leasehold',
    epc: 'D',
    isUnlicensedHmo: false,
    floodRisk: 'Low',
    notes: 'Heritage facade — maintenance budget review pending.',
  },
  {
    id: 'p-013',
    address: '60 Buchanan Street',
    city: 'Glasgow',
    postcode: 'G1 3HL',
    lat: 55.8612,
    lng: -4.2540,
    severity: 'Medium',
    dateAdded: daysAgo(6),
    signalType: 'Valuation drop',
    workflowStatus: 'In review',
    assignedTo: 'Risk Team',
    type: 'Retail',
    bedrooms: 0,
    bathrooms: 2,
    sqft: 4400,
    yearBuilt: 1972,
    estimatedValue: 1850000,
    lastValuation: daysAgo(12),
    tenure: 'Leasehold',
    epc: 'E',
    isUnlicensedHmo: false,
    floodRisk: 'Medium',
    notes: 'Footfall declining. Repositioning study commissioned.',
  },
  {
    id: 'p-014',
    address: '2 Marine Parade',
    city: 'Brighton',
    postcode: 'BN2 1TJ',
    lat: 50.8198,
    lng: -0.1357,
    severity: 'High',
    dateAdded: daysAgo(9),
    signalType: 'Flood risk change',
    workflowStatus: 'Action required',
    assignedTo: 'Risk Team',
    type: 'Hotel',
    bedrooms: 28,
    bathrooms: 30,
    sqft: 18500,
    yearBuilt: 1864,
    estimatedValue: 9800000,
    lastValuation: daysAgo(18),
    tenure: 'Freehold',
    epc: 'D',
    isUnlicensedHmo: false,
    floodRisk: 'High',
    notes: 'Coastal erosion monitoring active.',
  },
  {
    id: 'p-015',
    address: '14 Park Street',
    city: 'Bristol',
    postcode: 'BS1 5JA',
    lat: 51.4554,
    lng: -2.6066,
    severity: 'Medium',
    dateAdded: daysAgo(60),
    signalType: 'Underinsurance',
    workflowStatus: 'Awaiting customer',
    assignedTo: 'Priya Patel',
    type: 'Mixed Use',
    bedrooms: 2,
    bathrooms: 3,
    sqft: 2900,
    yearBuilt: 1925,
    estimatedValue: 1120000,
    lastValuation: daysAgo(65),
    tenure: 'Freehold',
    epc: 'C',
    isUnlicensedHmo: true,
    floodRisk: 'Medium',
    notes: 'Ground-floor retail performing well.',
  },
  {
    id: 'p-016',
    address: '88 Belgrave Square',
    city: 'London',
    postcode: 'SW1X 8PP',
    lat: 51.4996,
    lng: -0.1545,
    severity: 'Critical',
    dateAdded: daysAgo(4),
    signalType: 'Underinsurance',
    workflowStatus: 'Action required',
    assignedTo: 'Sarah Lee',
    type: 'Mansion',
    bedrooms: 7,
    bathrooms: 6,
    sqft: 6200,
    yearBuilt: 1840,
    estimatedValue: 28500000,
    lastValuation: daysAgo(7),
    tenure: 'Freehold',
    epc: 'F',
    isUnlicensedHmo: false,
    floodRisk: 'Low',
    notes: 'Sanctions exposure flagged on prior owner. Legal review required.',
  },
];
